### ISSUE TITLE
segfault on basic input

### ISSUE THREAD

**Issue by marionelstrt** [Lurik13/libft#1]
segfault on strlen when using NULL as a parameter, e.g. :

int main() {
	char *str = NULL;
	printf("%lu", ft_strlen(str));
}

https://en.wikipedia.org/wiki/Segmentation_fault

**Comment by demostanis** [comment]
broooo

**Comment by demostanis** [comment]
inadmissible

**Comment by Lurik13** [comment]
I've corrected a few functions that had the same problem.

**Comment by demostanis** [comment]
mais non fallait pas corriger ça
